# Puerto de ejecucion del servidor
server.port=8080

# Desactivar la cache de Thymeleaf para visualizar cambios en el HTML/CSS al instante
spring.thymeleaf.cache=false

# Conexion a la base de datos H2
spring.datasource.url=jdbc:h2:mem:dogtorsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola grafica de H2 (acceder en /h2)
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# JPA: cada vez que se ejecute Spring Boot, se borra y recrea la base de datos
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar las consultas SQL que JPA ejecuta por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true